---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 1
        timeout: 300
     
  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    # Add more env vars here
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./modules/domain/**/*.entity{.ts,.js}
    - TYPEORM_HOST: database-1.c4lwi5pvuofv.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: password
    - TYPEORM_DATABASE: glee

  roles:
    # Your code here
    - configure-server